--- #YAML:1.0
name:                Catalyst-Controller-DBIC-Transaction
version:             0.4
abstract:            Encloses actions into transactions
license:             ~
author:              
    - Daniel Ruoso <daniel@ruoso.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst::Runtime:             5.7011
    MRO::Compat:                   0
    Sub::Name:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
